In [249]:
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
import tensorflow as tf

In [257]:
import sklearn
sklearn.__version__

'0.23.1'

In [254]:
tf.__version__

'2.3.1'

In [255]:
np.__version__

'1.18.3'

In [256]:
pd.__version__

'1.0.4'

# Data preprocessing

In [124]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [125]:
X = dataset.iloc[:,3:-1]
y = dataset.iloc[:,-1]

#### encode gender labels

In [126]:
le = LabelEncoder()
X.iloc[:, 2] = le.fit_transform(X.iloc[:, 2])

In [127]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

#### encode country lables using OneHotEncoder class

In [128]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [129]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

# Spliting the dataset into train and test

In [130]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Feature scaling

In [131]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# ANN

In [132]:
ann = tf.keras.models.Sequential()

In [133]:
# add the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [134]:
# add the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [135]:
# add the output hidden layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [138]:
# compile ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [139]:
# train
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5233 - accuracy: 0.7886
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4649 - accuracy: 0.7983
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4369 - accuracy: 0.8039
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4223 - accuracy: 0.8160
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4133 - accuracy: 0.8199
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4071 - accuracy: 0.8219
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4016 - accuracy: 0.8238
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3970 - accuracy: 0.8255
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3920 - accuracy: 0.8267
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3878 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3382 - accuracy: 0.8620
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3381 - accuracy: 0.8621
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3378 - accuracy: 0.8606
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3378 - accuracy: 0.8609
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3374 - accuracy: 0.8608
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3383 - accuracy: 0.8600
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 0.8599
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3378 - accuracy: 0.8620
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3370 - accuracy: 0.8634
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3372 - accuracy: 

In [146]:
# predict result for user with data:
#  Geography: France, Credit Score: 600, Gender: Male, Age: 40, Tenure: 3, Balance: 60000, Number of products: 2, Credit card: yes, Active member: yes, Estimated Salary: 50000

observation = sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000 ]])
ann.predict(observation)

array([[0.03854331]], dtype=float32)

# Predicting the test set results

In [248]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.values.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Making the confusion matrix

In [263]:
cm = confusion_matrix(y_pred, y_test)
print(cm)
accuracy_score(y_pred, y_test, )

[[1511  196]
 [  84  209]]


0.86